#!/bin/sh
# Author: MarkusWessjohann
# Date: 19.10.2018
# Desc: Metric git keyword substitution cleaning
#       Removes Complexity, # Commits, loc and techn. debt

. metricUpdateFunc.sh

file="$1"

sed \
  -e "s/$metricPatternClean/\1\2/" \
  -e "s/$locPatternClean/\1\2/" \
  -e "s/$commitPatternClean/\1\2/" \
  -e "s/$lineDiffPatternClean/\1\2/" \
  -e "s/$techDebtPatternClean/\1\2/" 
