#!/bin/sh
# Author: MarkusWessjohann
# Date: 19.10.2018
# Desc: Metric git keyword substitution cleaning
#       Removes Complexity and # Commits

. metricUpdateFunc.sh

file="$1"

sed \
  -e "s/$metricPatternClean/\1\2/" \
  -e "s/$commitPatternClean/\1\2/" 
