#!/usr/bin/awk -f
# Author: MarkusWessjohann
# Date: 19.10.2018
# Desc: Metric git keyword substitution Smudge
#       Inserts the Complexity and LOC

BEGIN {
loc=0;
metricLineNr=0;
complexity=0; 
benchmarkComplexity=1500; 
benchmarkLoc=1000; 
}

// { line[NR]=$0 ;}
/^[\t]*/ { match($0, "[^\t]");complexity+=RSTART;}
/^[ ]*/ { match($0, "[^ ]");complexity+=(RSTART/2);}
/# Metric *:.*#/ {metricLineNr=NR}

END { 
loc=NR; 
date=strftime("%Y-%m-%d")
if (metricLineNr> 0) {
  newString=sprintf("# Metric  : %s Complexity: %4d <! %4d Loc: %4d <! %4d #", date, complexity, benchmarkComplexity, loc, benchmarkLoc);
  sub("# Metric *:.*#", newString, line[metricLineNr]);
}
for(i=1;i<=NR;i++) 
  printf("%s\n",line[i]);
}

