#!/bin/sh
# Author: MarkusWessjohann
# Date: 19.10.2018
# Desc: Metric git keyword substitution post-rebase hook
#       Inserts # Commits

. metricUpdateFunc.sh

echo "---------------------------------"
for file in `git diff-tree -r --name-only --no-commit-id HEAD`
do 
  [ -f "$file" ] || continue
  countCommits "$file"
  filename=`basename "$file"`
  setCommitSubstitution
  cat "$file" | 
	sed "s/$commitPattern/$commitSubstitution/" > "/tmp/$filename"
  mv "/tmp/$filename" "$file"
done

echo "---------------------------------"
